Fri Sep  9 03:22:51 2022 - INFO  - Start environmental preparation.
Traceback (most recent call last):
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 168, in <module>
    exitcode, output = rpm_install(args.pkgs, args.node, args.tempfile)
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 66, in rpm_install
    conn = ssh_cmd.pssh_conn(
  File "/root/GitRepo/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib64/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Failed to start firewalld.service: Unit firewalld.service not found.
Fri Sep  9 03:23:45 2022 - INFO  - End of environmental preparation!
Fri Sep  9 03:23:46 2022 - INFO  - Start executing testcase.
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Fri Sep  9 03:23:47 2022 - ERROR - Failed in remote CMD operation:1
sudo: firewall-cmd: command not found
Fri Sep  9 03:23:47 2022 - ERROR - oe_test_firewalld_add_newservice.sh line 37
sudo: firewall-cmd: command not found
sudo: firewall-cmd: command not found
sudo: firewall-cmd: command not found
sudo: firewall-cmd: command not found
sudo: firewall-cmd: command not found
sudo: firewall-cmd: command not found
Fri Sep  9 03:23:49 2022 - ERROR - oe_test_firewalld_add_newservice.sh line 44
sudo: firewall-cmd: command not found
Fri Sep  9 03:23:50 2022 - ERROR - oe_test_firewalld_add_newservice.sh line 46
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Fri Sep  9 03:23:51 2022 - ERROR - Failed in remote CMD operation:1
Fri Sep  9 03:23:51 2022 - ERROR - oe_test_firewalld_add_newservice.sh line 48
Fri Sep  9 03:23:52 2022 - ERROR - oe_test_firewalld_add_newservice.sh line 50
sudo: firewall-cmd: command not found
Fri Sep  9 03:23:53 2022 - ERROR - oe_test_firewalld_add_newservice.sh line 61
sudo: firewall-cmd: command not found
sudo: firewall-cmd: command not found
Fri Sep  9 03:23:54 2022 - ERROR - oe_test_firewalld_add_newservice.sh line 64
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Fri Sep  9 03:23:55 2022 - ERROR - Failed in remote CMD operation:1
Fri Sep  9 03:23:56 2022 - ERROR - oe_test_firewalld_add_newservice.sh line 66
Fri Sep  9 03:23:56 2022 - ERROR - oe_test_firewalld_add_newservice.sh line 68
Fri Sep  9 03:23:57 2022 - INFO  - Finish testcase execution.
Fri Sep  9 03:23:58 2022 - ERROR - failed to execute the case.
Fri Sep  9 03:23:59 2022 - INFO  - start environment cleanup.
sudo: firewall-cmd: command not found
sudo: firewall-cmd: command not found
sudo: firewall-cmd: command not found
sudo: firewall-cmd: command not found
sudo: firewall-cmd: command not found
Failed to start firewalld.service: Unit firewalld.service not found.
Traceback (most recent call last):
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 134, in rpm_remove
    conn = ssh_cmd.pssh_conn(
  File "/root/GitRepo/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib64/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Fri Sep  9 03:24:15 2022 - INFO  - Finish environment cleanup!
