Mon Sep 12 16:30:02 2022 - INFO  - Start to config params of the case.
Mon Sep 12 16:30:03 2022 - INFO  - End to config params of the case.
Mon Sep 12 16:30:04 2022 - INFO  - Start environmental preparation.
oe_test_nftables_create_counters.sh: line 33: /var/www/html/hello.html: No such file or directory
chmod: cannot access '/var/www/html/hello.html': No such file or directory
Failed to start httpd.service: Unit httpd.service not found.
oe_test_nftables_create_counters.sh: line 36: nft: command not found
oe_test_nftables_create_counters.sh: line 37: nft: command not found
Mon Sep 12 16:30:43 2022 - INFO  - End of environmental preparation!
Mon Sep 12 16:30:44 2022 - INFO  - Start executing testcase.
oe_test_nftables_create_counters.sh: line 43: nft: command not found
oe_test_nftables_create_counters.sh: line 44: nft: command not found
/root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh: line 37: [: too many arguments
Mon Sep 12 16:30:45 2022 - ERROR - oe_test_nftables_create_counters.sh line 45
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 80 after 29 ms: Connection refused
oe_test_nftables_create_counters.sh: line 48: nft: command not found
/root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh: line 37: [: too many arguments
Mon Sep 12 16:30:47 2022 - INFO  - Finish testcase execution.
Mon Sep 12 16:30:48 2022 - ERROR - failed to execute the case.
Mon Sep 12 16:30:49 2022 - INFO  - start environment cleanup.
oe_test_nftables_create_counters.sh: line 55: nft: command not found
Traceback (most recent call last):
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
OSError: [Errno 36] File name too long: "Last metadata expiration check: 0:00:26 ago on Mon 12 Sep 2022 04:30:15 PM CST.\nError: \n Problem: conflicting requests\n  - nothing provides system-logos needed by httpd-2.4.51-6.oe2209.riscv64\n(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)"
Mon Sep 12 16:30:52 2022 - INFO  - Finish environment cleanup!
