Fri Sep  9 03:25:10 2022 - INFO  - Start environmental preparation.
Traceback (most recent call last):
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 168, in <module>
    exitcode, output = rpm_install(args.pkgs, args.node, args.tempfile)
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 66, in rpm_install
    conn = ssh_cmd.pssh_conn(
  File "/root/GitRepo/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib64/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Failed to start firewalld.service: Unit firewalld.service not found.
Fri Sep  9 03:25:56 2022 - INFO  - End of environmental preparation!
Fri Sep  9 03:25:56 2022 - INFO  - Start executing testcase.
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Fri Sep  9 03:25:57 2022 - ERROR - Failed in remote CMD operation:1
Fri Sep  9 03:25:58 2022 - ERROR - oe_test_firewalld_addport_udp.sh line 34
sudo: firewall-cmd: command not found
Fri Sep  9 03:25:59 2022 - ERROR - oe_test_firewalld_addport_udp.sh line 38
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]Fri Sep  9 03:26:00 2022 - ERROR - Failed in remote CMD operation:1
Fri Sep  9 03:26:00 2022 - ERROR - oe_test_firewalld_addport_udp.sh line 40
Fri Sep  9 03:26:01 2022 - ERROR - oe_test_firewalld_addport_udp.sh line 42
Fri Sep  9 03:26:01 2022 - INFO  - Finish testcase execution.
Fri Sep  9 03:26:02 2022 - ERROR - failed to execute the case.
Fri Sep  9 03:26:03 2022 - INFO  - start environment cleanup.
sudo: firewall-cmd: command not found
sudo: firewall-cmd: command not found
Failed to start firewalld.service: Unit firewalld.service not found.
oe_test_firewalld_addport_udp.sh: line 46:  1125 Killed                  nc -4u -l 5555 > /tmp/nc_log
Traceback (most recent call last):
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 134, in rpm_remove
    conn = ssh_cmd.pssh_conn(
  File "/root/GitRepo/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib64/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Fri Sep  9 03:26:28 2022 - INFO  - Finish environment cleanup!
